version: "3.7"
networks:
  webnet:
    driver: bridge

services:
  web:
    restart: always
    build: .
    volumes:
      - .:/app
    environment:
      - MONGO_LINK=${MONGO_LINK}
      - BOOK_PW=${BOOK_PW}
      - BOOKING_DEBUG=false
    networks:
      - webnet
  
  nginx:
    restart: always
    image: nginx:mainline-alpine3.18-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./key:/etc/nginx/key
    depends_on:
      - web
    networks:
      - webnet