version: "3.7"
networks:
  webnet:
    driver: bridge

services:
  mongo:
    restart: always
    image: mongo:4.4.6
    networks:
      - webnet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword

  web:
    restart: always
    build: .
    volumes:
      - .:/app
    environment:
      - MONGO_LINK=mongodb://admin:adminpassword@mongo:27017
      - BOOK_PW=any_password
    networks:
      - webnet
    ports:
      - "8080:8080"
    depends_on:
      - mongo